apiVersion: apps/v1
kind: Deployment
metadata:
  name: genomic-analysis
spec:
  replicas: 3
  selector:
    matchLabels:
      app: genomic-analysis
  template:
    metadata:
      labels:
        app: genomic-analysis
    spec:
      containers:
      - name: app
        image: genomic-analysis:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: genomic-analysis
spec:
  selector:
    app: genomic-analysis
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
